services:
  open:
    image: zeroweb-app-open:latest
    build:
      context: ..
      dockerfile: apps/open/Dockerfile
      args:
        - NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY:-https://registry.npmmirror.com}
        - BASE_URI=${BASE_URI:-}
        - BASE_URL=${RELATIVE_PATH:-/}${BASE_URI:-}
